### ISSUE TITLE
Click loop

### ISSUE THREAD

**Issue by triptec** [scribe-analytics/scribe-analytics#2]
Hello, I've tried this script and it seems to work nicely except for a click loop that we're experiencing, it seems to be a problem when a user clicks a link to another site.

I think it's https://github.com/scribe-analytics/scribe-analytics/blob/master/src/scribe-analytics.js#L1183,
I'm thinking one might add a option like waitOnTracker and have a if clause around e.preventDefault() on https://github.com/scribe-analytics/scribe-analytics/blob/master/src/scribe-analytics.js#L1170 and around DomUtil.simulateMouseEvent(target, 'click'); on https://github.com/scribe-analytics/scribe-analytics/blob/master/src/scribe-analytics.js#L1183, thoughts?

**Comment by jdegoes** [comment]
I am happy to merge a tested pull request that fixes this problem.

**Comment by triptec** [comment]
I'm got some problems running the tests with grunt..
Running "nodeunit:all" (nodeunit) task
[D] Task source: /Users/andreas/Documents/Development/Mittmedia/scribe-analytics/node_modules/grunt-contrib-nodeunit/tasks/nodeunit.js
Fatal error: window is not defined

You got any idea?
